# Use the official Prometheus base image
FROM prom/prometheus:latest

# Set the working directory
WORKDIR /etc/prometheus

# Copy the Prometheus configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose Prometheus web UI port
EXPOSE 9090

# Start Prometheus
ENTRYPOINT [ "/bin/prometheus" ]
CMD [ "--config.file=/etc/prometheus/prometheus.yml", "--web.enable-lifecycle" ]
