apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: demo-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: demo-app-secrets
                  key: MYSQL_HOST
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: demo-app-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: demo-app-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-secrets
                  key: MYSQL_PASSWORD
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                secretKeyRef:
                  name: demo-app-secrets
                  key: KAFKA_ADVERTISED_LISTENERS
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
