global:
  scrape_interval: 5s  # How often Prometheus scrapes targets

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]

  - job_name: "zookeeper"
    static_configs:
      - targets: ["zookeeper:2181"]

  - job_name: "demo-app"
    static_configs:
      - targets: ["demo-app:2020"]
