spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:172.16.97.42}:3306/mydb
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:userpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
    stock-sheet-url: https://docs.google.com/spreadsheets/d/e/2PACX-1vTVvpOPIz0e1k3fAbExvEpo2XMGmVkhXPkUxnIEr4BVQayT2--uuxoqhc6yKBd7S_WG4SQOdJLEboqs/pub?gid=49957058&single=true&output=csv
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_ADVERTISED_LISTENERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: "createTransactionRequest:com.example.demo.dto.TradeRequestDTO"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "createTransactionRequest:com.example.demo.dto.TradeRequestDTO"
logging:
  level:
    org:
      hibernate.SQL: debug
